{% set version = '0.1.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-polite
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/polite_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/polite/polite_{{ version }}.tar.gz
  sha256: d2f7c256e886e1d541d67bfdc1429861aa8b94eb2f106d717d13b41f6ac51f4c

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-httr
    - r-magrittr
    - r-memoise
    - r-ratelimitr
    - r-robotstxt
    - r-rvest
    - r-usethis
  run:
    - r-base
    - r-httr
    - r-magrittr
    - r-memoise
    - r-ratelimitr
    - r-robotstxt
    - r-rvest
    - r-usethis

test:
  commands:
    - $R -e "library('polite')"           # [not win]
    - "\"%R%\" -e \"library('polite')\""  # [win]

about:
  home: https://github.com/dmi3kno/polite, https://dmi3kno.github.io/polite/
  license: MIT
  summary: 'Be responsible when scraping data from websites by following polite principles: introduce
    yourself, ask for permission, take slowly and never ask twice.'
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
