{% set version = "0.1.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-polite
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/polite_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/polite/polite_{{ version }}.tar.gz
  sha256: 0d54bbc0dbe747f437eb5b6ed004ba5fe4c8d344a5d679f7d16159d14dc2e0ee

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-httr
    - r-magrittr
    - r-memoise
    - r-ratelimitr
    - r-robotstxt
    - r-rvest
    - r-usethis
  run:
    - r-base
    - r-httr
    - r-magrittr
    - r-memoise
    - r-ratelimitr
    - r-robotstxt
    - r-rvest
    - r-usethis

test:
  commands:
    - $R -e "library('polite')"           # [not win]
    - "\"%R%\" -e \"library('polite')\""  # [win]

about:
  home: https://github.com/dmi3kno/polite, https://dmi3kno.github.io/polite/
  license: MIT
  summary: 'Be responsible when scraping data from websites by following polite principles: introduce yourself, ask for permission, take slowly and never ask twice.'
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
